[2023-12-05T08:38:03.246+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_to_psql.ingest manual__2023-12-05T08:08:37.997322+00:00 [queued]>
[2023-12-05T08:38:03.263+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_to_psql.ingest manual__2023-12-05T08:08:37.997322+00:00 [queued]>
[2023-12-05T08:38:03.264+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-12-05T08:38:03.293+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ingest> on 2023-12-05 08:08:37.997322+00:00
[2023-12-05T08:38:03.309+0000] {standard_task_runner.py:57} INFO - Started process 474 to run task
[2023-12-05T08:38:03.318+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_local_to_psql', 'ingest', 'manual__2023-12-05T08:08:37.997322+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/etl_local_to_psql.py', '--cfg-path', '/tmp/tmpc9amjuaw']
[2023-12-05T08:38:03.391+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask ingest
[2023-12-05T08:38:03.554+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_local_to_psql.ingest manual__2023-12-05T08:08:37.997322+00:00 [running]> on host dabe3da44d20
[2023-12-05T08:38:03.761+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-05T08:38:04.333+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_local_to_psql' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-12-05T08:08:37.997322+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-05T08:08:37.997322+00:00'
[2023-12-05T08:38:04.335+0000] {logging_mixin.py:154} INFO - yellow_ny_taxi_2023_12 /opt/***/output_2023-12.parquet 2023-12-05T08:08:37.997322+00:00
[2023-12-05T08:38:04.359+0000] {logging_mixin.py:154} INFO - connection established successfully, inserting data...
[2023-12-05T08:38:04.366+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 22, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2023-12-05T08:38:04.396+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_local_to_psql, task_id=ingest, execution_date=20231205T080837, start_date=20231205T083803, end_date=20231205T083804
[2023-12-05T08:38:04.432+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task ingest ('DataFrame' object has no attribute 'tpep_pickup_datetime'; 474)
[2023-12-05T08:38:04.493+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-05T08:38:04.553+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
